default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: sumon
  password: 1122
  host: localhost
  port: 5432

development:
  <<: *default
  database: hello_react_rails_two

test:
  <<: *default
  database: hello_react_rails_two_test

production:
  <<: *default
  database: hello_react_rails_two_production